"""Generated from api/contracts/internal-insights/v1/openapi.yaml; do not edit."""

CONTRACT_VERSION = "1.0.0"
ANNIVERSARIES_PATH = "/api/internal/insights/anniversaries"
ARTIST_CENTRALITY_PATH = "/api/internal/insights/artist-centrality"
COMMUNITY_ENRICHMENT_PATH = "/api/internal/insights/community-enrichment"
DATA_COMPLETENESS_PATH = "/api/internal/insights/data-completeness"
GENRE_TRENDS_PATH = "/api/internal/insights/genre-trends"
LABEL_LONGEVITY_PATH = "/api/internal/insights/label-longevity"
RARITY_SCORES_PATH = "/api/internal/insights/rarity-scores"
