---
name: 'Setup Just'
description: 'Install just task runner'
inputs:
  version:
    description: 'Version of just to install'
    required: false
    default: '1.38.0'

runs:
  using: 'composite'
  steps:
    - name: '🔧 Install just'
      shell: bash
      env:
        JUST_VERSION: ${{ inputs.version }}
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}
      run: |
        echo "Installing just version $JUST_VERSION..."

        # Determine OS and architecture
        case "$RUNNER_OS" in
          Linux)
            PLATFORM="x86_64-unknown-linux-musl"
            ;;
          macOS)
            if [[ "$RUNNER_ARCH" == "ARM64" ]]; then
              PLATFORM="aarch64-apple-darwin"
            else
              PLATFORM="x86_64-apple-darwin"
            fi
            ;;
          Windows)
            PLATFORM="x86_64-pc-windows-msvc"
            EXT=".zip"
            ;;
          *)
            echo "Unsupported OS: $RUNNER_OS"
            exit 1
            ;;
        esac

        # Download and install
        URL="https://github.com/casey/just/releases/download/$JUST_VERSION/just-$JUST_VERSION-${PLATFORM}.tar.gz"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          URL="https://github.com/casey/just/releases/download/$JUST_VERSION/just-$JUST_VERSION-${PLATFORM}.zip"
          curl -L -o just.zip "$URL"
          unzip -p just.zip just.exe > just.exe
          mkdir -p "$HOME/.local/bin"
          mv just.exe "$HOME/.local/bin/"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        else
          curl -L "$URL" | tar xz just
          chmod +x just
          sudo mv just /usr/local/bin/
        fi

        # Verify installation
        just --version
