# Example configuration for Rust Extractor

# RabbitMQ connection URL
amqp_connection = "amqp://localhost:5672"

# Path to store Discogs data
discogs_root = "/discogs-data"

# Maximum temporary file size in bytes
max_temp_size = 1000000000

# Days between periodic checks for new data
periodic_check_days = 15

# Port for health monitoring server
health_port = 8000

# Number of worker threads
max_workers = 8

# Batch size for AMQP messages
batch_size = 100

# Internal queue size for processing
queue_size = 5000

# How often to log progress (records)
progress_log_interval = 1000

# S3 bucket containing Discogs dumps
s3_bucket = "discogs-data-dumps"

# S3 region
s3_region = "us-west-2"
