---
name: "Setup Python and UV"
description: "Setup Python with UV package manager and caching"
author: "SimplicityGuy"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.13"
  cache-dependency-glob:
    description: "Glob pattern for cache dependencies"
    required: false
    default: "**/uv.lock"

runs:
  using: composite
  steps:
    - name: 📦 Install uv
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
      with:
        version: latest
        enable-cache: true
        cache-dependency-glob: ${{ inputs.cache-dependency-glob }}

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: 💾 Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-python-${{ inputs.python-version }}-${{ hashFiles('**/uv.lock', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ inputs.python-version }}-
          ${{ runner.os }}-python-
