---
name: Docker Image Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 15 * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Docker Image Cleanup
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          delete-partial-images: true
          delete-untagged: true
          keep-n-tagged: 2
          older-than: 30 days
          packages: dashboard,discovery,extractor,graphinator,tableinator
